name: Generate Snake GIF

on:
  schedule:
    - cron: '0 0 * * *'  # Ejecuta diariamente a medianoche
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Clonar el repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Generar la serpiente
    - name: Generate Snake GIF
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/github-snake.svg
          dist/github-snake-dark.svg?palette=github-dark
          dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    # 3️⃣ Subir el SVG al repositorio
    - name: Commit Snake SVG
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dist/github-snake.svg
        git add dist/github-snake-dark.svg
        git add dist/ocean.gif
        git commit -m "Update snake contribution graph" || echo "No changes to commit"
        git push
